"""initial schema

Revision ID: 65249856a9ba
Revises: 
Create Date: 2026-08-31 13:34:37.884186
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '65249856a9ba'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email', name=op.f('uq_app_user_email'))
    )
    op.create_table('push_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_push_token_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_push_token')),
    sa.UniqueConstraint('user_id', 'token', name=op.f('uq_push_token_user_id'))
    )
    op.create_table('subject',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Europe/Rome', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], name=op.f('fk_subject_owner_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subject'))
    )
    op.create_table('access_grant',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('grantee_user_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['app_user.id'], name=op.f('fk_access_grant_granted_by_user_id_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['grantee_user_id'], ['app_user.id'], name=op.f('fk_access_grant_grantee_user_id_app_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_access_grant_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_grant')),
    sa.UniqueConstraint('subject_id', 'grantee_user_id', name=op.f('uq_access_grant_subject_id'))
    )
    op.create_index(op.f('ix_access_grant_grantee_user_id'), 'access_grant', ['grantee_user_id'], unique=False)
    op.create_table('activity_baseline',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('hour_of_day', sa.SmallInteger(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('mean_value', sa.Float(), nullable=True),
    sa.Column('stddev_value', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_activity_baseline_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'hour_of_day', 'metric', name=op.f('pk_activity_baseline'))
    )
    op.create_table('activity_event',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('tier', sa.CHAR(length=1), nullable=False),
    sa.Column('confidence', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_activity_event_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_event')),
    sa.UniqueConstraint('subject_id', 'dedup_key', name=op.f('uq_activity_event_subject_id'))
    )
    op.create_index('ix_activity_event_subject_kind_time', 'activity_event', ['subject_id', 'kind', 'occurred_at'], unique=False)
    op.create_index('ix_activity_event_subject_tier_time', 'activity_event', ['subject_id', 'tier', 'occurred_at'], unique=False)
    op.create_table('alert_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('severity', sa.String(length=8), server_default='amber', nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_alert_rule_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rule'))
    )
    op.create_index(op.f('ix_alert_rule_subject_id'), 'alert_rule', ['subject_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_kind', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['app_user.id'], name=op.f('fk_audit_log_actor_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_audit_log_subject_id_subject'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index('ix_audit_log_actor_time', 'audit_log', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_log_subject_time', 'audit_log', ['subject_id', 'occurred_at'], unique=False)
    op.create_table('checkin_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('partial_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['app_user.id'], name=op.f('fk_checkin_request_requested_by_user_id_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_checkin_request_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkin_request'))
    )
    op.create_index('ix_checkin_request_subject_time', 'checkin_request', ['subject_id', 'requested_at'], unique=False)
    op.create_table('device',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('auth_token_hash', sa.Text(), nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=True),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('permissions_ok', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_device_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device'))
    )
    op.create_index(op.f('ix_device_subject_id'), 'device', ['subject_id'], unique=False)
    op.create_table('geofence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('center_lat', sa.Double(), nullable=False),
    sa.Column('center_lon', sa.Double(), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=16), server_default='safe', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_geofence_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geofence'))
    )
    op.create_index(op.f('ix_geofence_subject_id'), 'geofence', ['subject_id'], unique=False)
    op.create_table('location_fix',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lat', sa.Double(), nullable=False),
    sa.Column('lon', sa.Double(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.Column('battery_pct', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.String(length=16), server_default='phone', nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_location_fix_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_fix')),
    sa.UniqueConstraint('subject_id', 'dedup_key', name=op.f('uq_location_fix_subject_id'))
    )
    op.create_index('ix_location_fix_subject_time', 'location_fix', ['subject_id', 'occurred_at'], unique=False)
    op.create_table('alert_event',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dedup_key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_by_user_id', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['app_user.id'], name=op.f('fk_alert_event_acknowledged_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rule.id'], name=op.f('fk_alert_event_rule_id_alert_rule'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_alert_event_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_event')),
    sa.UniqueConstraint('subject_id', 'dedup_key', name=op.f('uq_alert_event_subject_id'))
    )
    op.create_index('ix_alert_event_subject_time', 'alert_event', ['subject_id', 'created_at'], unique=False)
    op.create_table('escalation_action',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('checkin_id', sa.UUID(), nullable=True),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=False),
    sa.Column('rung', sa.SmallInteger(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='sent', nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('signature', sa.String(length=64), server_default='', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checkin_id'], ['checkin_request.id'], name=op.f('fk_escalation_action_checkin_id_checkin_request'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_escalation_action_subject_id_subject'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['app_user.id'], name=op.f('fk_escalation_action_triggered_by_user_id_app_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalation_action'))
    )
    op.create_index('ix_escalation_action_subject_time', 'escalation_action', ['subject_id', 'created_at'], unique=False)
    op.create_table('geofence_state',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('geofence_id', sa.UUID(), nullable=False),
    sa.Column('is_inside', sa.Boolean(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_fix_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofence.id'], name=op.f('fk_geofence_state_geofence_id_geofence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_fix_id'], ['location_fix.id'], name=op.f('fk_geofence_state_last_fix_id_location_fix'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_geofence_state_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'geofence_id', name=op.f('pk_geofence_state'))
    )
    op.create_table('liveness_snapshot',
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_movement_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_vital_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('headline_state', sa.String(length=16), nullable=False),
    sa.Column('headline_color', sa.String(length=8), nullable=False),
    sa.Column('headline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('headline_evidence', sa.String(length=32), nullable=True),
    sa.Column('latest_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('latest_bpm_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latest_location_id', sa.BigInteger(), nullable=True),
    sa.Column('phone_battery_pct', sa.SmallInteger(), nullable=True),
    sa.Column('watch_likely_charging', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('pipeline_lag_seconds', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['latest_location_id'], ['location_fix.id'], name=op.f('fk_liveness_snapshot_latest_location_id_location_fix'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_liveness_snapshot_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', name=op.f('pk_liveness_snapshot'))
    )
    op.create_table('confirmation_response',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('escalation_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('response', sa.String(length=16), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=16), server_default='phone', nullable=False),
    sa.ForeignKeyConstraint(['escalation_id'], ['escalation_action.id'], name=op.f('fk_confirmation_response_escalation_id_escalation_action'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_confirmation_response_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_confirmation_response'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmation_response')
    op.drop_table('liveness_snapshot')
    op.drop_table('geofence_state')
    op.drop_index('ix_escalation_action_subject_time', table_name='escalation_action')
    op.drop_table('escalation_action')
    op.drop_index('ix_alert_event_subject_time', table_name='alert_event')
    op.drop_table('alert_event')
    op.drop_index('ix_location_fix_subject_time', table_name='location_fix')
    op.drop_table('location_fix')
    op.drop_index(op.f('ix_geofence_subject_id'), table_name='geofence')
    op.drop_table('geofence')
    op.drop_index(op.f('ix_device_subject_id'), table_name='device')
    op.drop_table('device')
    op.drop_index('ix_checkin_request_subject_time', table_name='checkin_request')
    op.drop_table('checkin_request')
    op.drop_index('ix_audit_log_subject_time', table_name='audit_log')
    op.drop_index('ix_audit_log_actor_time', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_alert_rule_subject_id'), table_name='alert_rule')
    op.drop_table('alert_rule')
    op.drop_index('ix_activity_event_subject_tier_time', table_name='activity_event')
    op.drop_index('ix_activity_event_subject_kind_time', table_name='activity_event')
    op.drop_table('activity_event')
    op.drop_table('activity_baseline')
    op.drop_index(op.f('ix_access_grant_grantee_user_id'), table_name='access_grant')
    op.drop_table('access_grant')
    op.drop_table('subject')
    op.drop_table('push_token')
    op.drop_table('app_user')
    # ### end Alembic commands ###
