"""device pairing codes

Revision ID: 6998aecc2329
Revises: 6bdde17a2eb4
Create Date: 2026-08-31 15:48:54.662307
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6998aecc2329'
down_revision: str | None = '6bdde17a2eb4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('pairing_code_hash', sa.String(length=64), nullable=True))
    op.add_column('device', sa.Column('pairing_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('device', sa.Column('paired_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('device', 'auth_token_hash',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_unique_constraint(op.f('uq_device_pairing_code_hash'), 'device', ['pairing_code_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_device_pairing_code_hash'), 'device', type_='unique')
    op.alter_column('device', 'auth_token_hash',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('device', 'paired_at')
    op.drop_column('device', 'pairing_expires_at')
    op.drop_column('device', 'pairing_code_hash')
    # ### end Alembic commands ###
