"""audio sessions

Revision ID: cb24fdb91d4e
Revises: 6998aecc2329
Create Date: 2026-08-31 21:41:26.396095
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'cb24fdb91d4e'
down_revision: str | None = '6998aecc2329'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('opened_by_user_id', sa.UUID(), nullable=False),
    sa.Column('escalation_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='offered', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('announced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_by', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['escalation_id'], ['escalation_action.id'], name=op.f('fk_audio_session_escalation_id_escalation_action'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opened_by_user_id'], ['app_user.id'], name=op.f('fk_audio_session_opened_by_user_id_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], name=op.f('fk_audio_session_subject_id_subject'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_session'))
    )
    op.create_index('ix_audio_session_subject_time', 'audio_session', ['subject_id', 'created_at'], unique=False)
    op.create_table('audio_signal',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['audio_session.id'], name=op.f('fk_audio_signal_session_id_audio_session'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audio_signal'))
    )
    op.create_index('ix_audio_signal_session_seq', 'audio_signal', ['session_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audio_signal_session_seq', table_name='audio_signal')
    op.drop_table('audio_signal')
    op.drop_index('ix_audio_session_subject_time', table_name='audio_session')
    op.drop_table('audio_session')
    # ### end Alembic commands ###
